name = "NeutrinoTelescopes"
uuid = "ef384c05-3785-4474-8b09-e6d5e3a3b215"
authors = ["Christian Haack <christian.haack@tum.de> and contributors"]
version = "0.1.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
BenchmarkPlots = "ab8c0f59-4072-4e0d-8f91-a91e1495eb26"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DTables = "20c56dc6-594c-4682-91cf-1d46875b1eba"
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EarlyStopping = "792122b4-ca99-40de-a6bc-6742525f08b6"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GaussianProcesses = "891a1506-143c-57d2-908e-e1f8e92e6de9"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Hyperopt = "93e5fe13-2215-51db-baaf-2e9a34fb2712"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NonNegLeastSquares = "b7351bd1-99d9-5c5d-8786-f205a815c4d7"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
ParameterSchedulers = "d7d3b36b-41b8-4d0d-a2bf-768c6151755e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Parquet = "626c502c-15b0-58ad-a749-f091afb673ae"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PoissonRandom = "e409e4f3-bfea-5376-8464-e040bb5c01ab"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SphereSurfaceHistogram = "b3f7556e-2c1d-50f9-83b1-7c1b68b21cf8"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TableTransforms = "0d432bfd-3ee1-4ac1-886a-39f05cc69a3e"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
Traceur = "37b6cedf-1f77-55f8-9503-c64b63398394"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
WaterLily = "ed894a53-35f9-47f1-b17f-85db9237eebd"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Arrow = "2"
BenchmarkTools = "1"
CUDA = "3"
DataFrames = "1"
FFTW = "1"
MLUtils = "0.4"
Optim = "1"
Pipe = "1"
Plots = "1"
Polynomials = "3"
QuadGK = "2"
Reexport = "1"
Revise = "3"
Roots = "2"
Sobol = "1"
SpecialFunctions = "2"
StaticArrays = "1"
Unitful = "1"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
